### ISSUE TITLE
Unexpected output: DEVTOOL_REGEX:

### ISSUE THREAD

**Issue by kentcdodds** [jonathanewerner/webpack-validator#15]
When adding this to my project, I suddenly start getting the output:

```
[index.js] DEVTOOL_REGEX:  /^(#@|@|#)?(eval|cheap-eval-source-map|cheap-source-map|cheap-module-eval-source-map|cheap-module-source-map|eval-source-map|source-map|hidden-source-map|inline-source-map)/
```

Any ideas why this may happen?

It's not breaking anything, but it's confusing and noise.

**Comment by jonathanewerner** [comment]
It was an accidental debug console.log, fixed in #12.

**Comment by kentcdodds** [comment]
Ah, ok, cool. Wondered why I couldn't find a console.log in the source :+1:

**Comment by kentcdodds** [comment]
With that, I think we're ready to go 1.0.0!

**Comment by jonathanewerner** [comment]
Aaaallright. :) Looking forward to turn semantic-release on.
