### ISSUE TITLE
Improvement ideas from webpack-doctor

### ISSUE THREAD

**Issue by bebraw** [jonathanewerner/webpack-validator#18]
Hi,

I planned to write a similar tool in the past but never got around to implementing the specification. See the [issues of the project](https://github.com/survivejs/webpack-doctor/issues). Those cover some of the common pain point. Just schema alone helps a lot.

**Comment by kentcdodds** [comment]
Awesome! That's really helpful @bebraw! Thanks!

**Comment by jonathanewerner** [comment]
Cool! Will def check this out.

**Comment by bebraw** [comment]
Do you want that I go through the issues and migrate the relevant ones here?

**Comment by jonathanewerner** [comment]
That would be super awesome!

**Comment by bebraw** [comment]
Ok, will do. Closing.
