### ISSUE TITLE
Implement a "bin" version

### ISSUE THREAD

**Issue by bebraw** [jonathanewerner/webpack-validator#52]
It would be good to have `webpack-validator`. You could run it against your configuration on commit/push for instance rather than when running webpack. Even this would be enough for common usage and avoid a little bit of overhead when running webpack normally.

**Comment by kentcdodds** [comment]
@nyrosmith was working on [something](https://github.com/nyrosmith/webpack-validator-cli) for [the original project](https://github.com/kentcdodds/webpack-validator-DEPRECATED/issues/5)

I think many people would use a CLI exclusively (probably myself included).

**Comment by nyrosmith** [comment]
@jonathanewerner Can you assign me to this issue?

**Comment by jonathanewerner** [comment]
Cool, looking forward to this. I added you as a collaborator again, Martin. 👍🏻

**Comment by kentcdodds** [comment]
Should we follow Sindre Sorhus's example and have a separate CLI repo/package? https://github.com/sindresorhus/ama/issues/17

**Comment by jonathanewerner** [comment]
I totally dig the arguments presented there. Let's do it. @nyrosmith would you be willing to create that repo?

**Comment by nyrosmith** [comment]
Yes, will create a new repo.
Quick question: how will we name it? webpack-validator-cli is ways to long. I would never use a tool with such a long Name...
Any suggestions?

**Comment by kentcdodds** [comment]
Nah, that's not too long at all... [validate-commit-msg](http://npm.im/validate-commit-msg), [eslint-find-new-rules](http://npm.im/eslint-find-new-rules) ¯\\\_(ツ)_/¯

**Comment by nyrosmith** [comment]
OK, I get it. Maybe I create an alias...

**Comment by jonathanewerner** [comment]
I like clarity too, so webpack-validator-cli -> 👍🏻. Easier to promote one "brand", too. :)

**Comment by sarbbottam** [comment]
If the cli will be accepting multiple options and arguments, https://github.com/yargs/yargs might be useful.

**Comment by kentcdodds** [comment]
I recommend npm.im/commander

**Comment by sarbbottam** [comment]
Didn't know about commander.

**Comment by sarbbottam** [comment]
@kentcdodds I am preferring npm.im/commander as it has way more less dependencies, rather just one.

**Comment by nyrosmith** [comment]
I used commander for my first approach and in my current solution. As long as I don't find limitations or something ways better I'll go my way with commander.

**Comment by nyrosmith** [comment]
I'll close this in favor of https://github.com/nyrosmith/webpack-validator-cli.
ATM there is just crap in my repofrom my very first attempt but I have a basic working solution on disc. As soon as I have feedback from https://github.com/jonathanewerner/webpack-validator/pull/55 I'll update my repo and let all of you know
