### ISSUE TITLE
Warn about near misspellings?

### ISSUE THREAD

**Issue by bebraw** [jonathanewerner/webpack-validator#61]
I wonder if there's some library that would allow us to match near misspellings and suggest the closest suitable entry. I.e. if you tried to enter `devServer.historyAPIFallback`, it would warn and point you to `devServer.historyApiFallback` instead. That feels like some distance calculation to me. The logic would kick in if the validator detects fields that aren't in the schema.

**Comment by nyrosmith** [comment]
I already have investigated and I think there is a suitable soultion. I am already into it

**Comment by jonathanewerner** [comment]
This is a duplicate of #14, no?

**Comment by bebraw** [comment]
Yeah, missed that. Oops.
